[workspace]
changelog_path = "CHANGELOG.md"
changelog_update = true
dependencies_update = true

git_release_enable = true
git_tag_enable = true
git_release_type = "auto"

release_always = false
publish = true
publish_timeout = "10m"

semver_check = true
release_commits = "^(release|feat)[(:]"
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
